export async function fetchSupplierProducts() {
  // Simule une grande liste de produits fournisseur
  return [
    {
      id: "A1",
      name: "Farine T45",
      category: "Epicerie",
      price: 2.5,
      stock: 120,
      unit: "kg",
      sku: "FAR-T45",
      vat_rate: 5.5,
    },
    {
      id: "A2",
      name: "Farine T55",
      category: "Epicerie",
      price: 2.7,
      stock: 80,
      unit: "kg",
      sku: "FAR-T55",
      vat_rate: 5.5,
    },
    {
      id: "B1",
      name: "Sucre semoule",
      category: "Epicerie",
      price: 1.8,
      stock: 200,
      unit: "kg",
      sku: "SUC-SEM",
      vat_rate: 5.5,
    },
    {
      id: "B2",
      name: "Sucre glace",
      category: "Epicerie",
      price: 2.0,
      stock: 150,
      unit: "kg",
      sku: "SUC-GLA",
      vat_rate: 5.5,
    },
    {
      id: "C1",
      name: "Sel fin",
      category: "Epicerie",
      price: 0.9,
      stock: 300,
      unit: "kg",
      sku: "SEL-FIN",
      vat_rate: 5.5,
    },
    {
      id: "C2",
      name: "Sel de Guérande",
      category: "Epicerie",
      price: 1.5,
      stock: 90,
      unit: "kg",
      sku: "SEL-GUE",
      vat_rate: 5.5,
    },
    {
      id: "D1",
      name: "Huile d'olive",
      category: "Huiles",
      price: 6.5,
      stock: 60,
      unit: "L",
      sku: "HUI-OLI",
      vat_rate: 5.5,
    },
    {
      id: "D2",
      name: "Huile de tournesol",
      category: "Huiles",
      price: 3.2,
      stock: 110,
      unit: "L",
      sku: "HUI-TOU",
      vat_rate: 5.5,
    },
    {
      id: "E1",
      name: "Lait entier",
      category: "Produits laitiers",
      price: 1.1,
      stock: 250,
      unit: "L",
      sku: "LAI-ENT",
      vat_rate: 5.5,
    },
    {
      id: "E2",
      name: "Lait demi-écrémé",
      category: "Produits laitiers",
      price: 1.0,
      stock: 300,
      unit: "L",
      sku: "LAI-DEM",
      vat_rate: 5.5,
    },
    {
      id: "F1",
      name: "Beurre doux",
      category: "Produits laitiers",
      price: 2.3,
      stock: 130,
      unit: "kg",
      sku: "BEU-DOU",
      vat_rate: 5.5,
    },
    {
      id: "F2",
      name: "Beurre demi-sel",
      category: "Produits laitiers",
      price: 2.4,
      stock: 120,
      unit: "kg",
      sku: "BEU-DEM",
      vat_rate: 5.5,
    },
    {
      id: "G1",
      name: "Œufs frais",
      category: "Produits frais",
      price: 0.18,
      stock: 1000,
      unit: "pièce",
      sku: "OEU-FRA",
      vat_rate: 5.5,
    },
    {
      id: "H1",
      name: "Levure boulangère",
      category: "Epicerie",
      price: 0.7,
      stock: 70,
      unit: "sachet",
      sku: "LEV-BOU",
      vat_rate: 5.5,
    },
    {
      id: "I1",
      name: "Crème liquide",
      category: "Produits laitiers",
      price: 1.6,
      stock: 90,
      unit: "L",
      sku: "CRE-LIQ",
      vat_rate: 5.5,
    },
    {
      id: "J1",
      name: "Chocolat noir",
      category: "Epicerie",
      price: 3.5,
      stock: 60,
      unit: "kg",
      sku: "CHO-NOI",
      vat_rate: 5.5,
    },
    {
      id: "J2",
      name: "Chocolat au lait",
      category: "Epicerie",
      price: 3.7,
      stock: 55,
      unit: "kg",
      sku: "CHO-LAI",
      vat_rate: 5.5,
    },
    {
      id: "K1",
      name: "Yaourt nature",
      category: "Produits laitiers",
      price: 0.5,
      stock: 400,
      unit: "pièce",
      sku: "YAO-NAT",
      vat_rate: 5.5,
    },
    {
      id: "L1",
      name: "Pain de mie",
      category: "Boulangerie",
      price: 1.2,
      stock: 180,
      unit: "kg",
      sku: "PAI-MIE",
      vat_rate: 5.5,
    },
    {
      id: "M1",
      name: "Jambon blanc",
      category: "Charcuterie",
      price: 12.0,
      stock: 40,
      unit: "kg",
      sku: "JAM-BLA",
      vat_rate: 5.5,
    },
    // ...ajoute autant de produits que tu veux !
  ];
}

export async function fetchSupplierInfo() {
  return {
    id: "SUP1",
    name: "Fournisseur Pro Alimentaire",
    contact: "contact@fournisseurpro.com",
    address: "12 rue des Marchés, 75000 Paris",
    phone: "01 23 45 67 89",
    website: "https://fournisseurpro.com",
  };
}

export async function fetchSupplier2Products() {
  // Simule une autre liste de produits fournisseur
  return [
    {
      id: "X1",
      name: "Tomates cerises",
      category: "Légumes",
      price: 3.0,
      stock: 150,
      unit: "kg",
      sku: "TOM-CER",
      vat_rate: 5.5,
    },
    {
      id: "X2",
      name: "Concombres",
      category: "Légumes",
      price: 1.5,
      stock: 100,
      unit: "kg",
      sku: "CON-COM",
      vat_rate: 5.5,
    },
    {
      id: "Y1",
      name: "Pommes Gala",
      category: "Fruits",
      price: 2.2,
      stock: 200,
      unit: "kg",
      sku: "POM-GAL",
      vat_rate: 5.5,
    },
    {
      id: "Y2",
      name: "Bananes",
      category: "Fruits",
      price: 1.8,
      stock: 180,
      unit: "kg",
      sku: "BAN-BAN",
      vat_rate: 5.5,
    },
    {
      id: "Z1",
      name: "Poulet entier",
      category: "Viandes",
      price: 5.5,
      stock: 75,
      unit: "kg",
      sku: "POU-ENT",
      vat_rate: 5.5,
    },
    {
      id: "Z2",
      name: "Steaks hachés",
      category: "Viandes",
      price: 8.0,
      stock: 60,
      unit: "kg",
      sku: "STE-HAC",
      vat_rate: 5.5,
    },
  ];
}
export async function fetchSupplier2Info() {
  return {
    id: "SUP2",
    name: "Fournisseur Fraîcheur",
    contact: "contact@fournisseurfraicheur.com",
    address: "45 avenue des Fleurs, 75000 Paris",
    phone: "01 98 76 54 32",
    website: "https://fournisseurfraicheur.com",
  };
}
